### ISSUE TITLE
Getting the best move blocks the app from running and stockfish breaking on hot reload

### ISSUE THREAD

**Issue by FirePlank** [loloof64/React-Native-Stockfish-Android#2]
Hi! Great app you have except I'm having a few issue with it. 

I took the searchBestMove function from your example and integrated it with my chessboard GUI. I wanted to make it have constant analysis of the position showcasing the pv and current evaluation as I'm making the moves on the board similar to the analysis https://lichess.org/analysis provides. I'm able to just run `go depth 20` and parse the `info` log to get the pv and current evaluation but the problem is that the app freezes and while I'm able to somewhat drag the pieces around as soon as I try to move it to any one square it freezes and only when the engine reaches depth 20 does it make the move and I can continue. In the docs for `await mainLoop()` you state "Also, you'd better launch this command in a new "thread"." but how do I do that if react-native is single threaded. I couldn't find any way to run it on a new thread to make it non blocking.

Also another issue is that whenever I edit any code whatsoever in my react-native app and it hot reloads the engine breaks completely and I'm unable to communicate with it. it just prints `Stockfish by the Stockfish developers (see AUTHORS file)` and nothing else. I have to reset the entire app to continue which is very annoying, do you have any way around this?

**Comment by loloof64** [comment]
Hi !

Thank you for your interest in my package. It's been a while since I've stopped using this library myself, so I'll try to help you as far  as I can.

> I couldn't find any way to run it on a new thread to make it non blocking.

Indeed, I could have the plugin I used as an example for that in the documentation : [React Native Threads](https://www.npmjs.com/package/react-native-threads).

Also keeps in mind that this plugin is using the old architecture of React-Native, while a new architecture based on TurboModules has came our about one-two years ago. I don't plan to release a new version based on it, as for now I target another framework (Flutter and Dart).

Anyway, good luck for your experimentations and your project.

**Comment by loloof64** [comment]
I forgot to say, that using hot reload should be avoided when developing with my plugin.
Unfortunately, I did not find a workaround for this.

In more details : I've imported the C++ code from Stockfish with little modifications, but at the cost that the application must be run from start to end, which is not exactly the case with hot-reload.
There could be a way to avoid this : but this has two drawbacks
1. This involves more works to adapt the original stockfish code for React-Native
2. And as a consequence, someone which wants to use later versions of Stockfish will have more trouble to integrate the sources in my plugin.

**Comment by FirePlank** [comment]
> Indeed, I could have the plugin I used as an example for that in the documentation : [React Native Threads](https://www.npmjs.com/package/react-native-threads).

Yes, I did see this package but I was unsure if I was able to use it for this package since the instructions seem complex and it stating `only the official react native modules are available from your threads` which this is not. Any way you can explain how I can setup react native threads for your library? How will calling stuff like sendCommand work if i make the mainLoop start in a thread. I tried making some changes to the StockfishChessEngineModule.java file to make that threaded with the help of ChatGPT but the changes seem to not be reflected upon rebooting the app or rerunning the `npx expo start --dev-client`

> using hot reload should be avoided when developing with my plugin.

That is unfortunate as hot reloading is a core part of react native but I'm willing to restart the app when developing the stockfish implementation if needed.

**Comment by loloof64** [comment]
Hi again

In fact, if you look closely in the example folder, you can see that react native threads package is not used, but instead I set up some listeners.

Please, have a look a this example subfolder.

**Comment by FirePlank** [comment]
Yes, I have copied the code from the example folder but it makes the app freeze from user interactions while stockfish is looking for the best move, that's why i am wondering if the package you linked is the only way and if so, could you help me set it up?

**Comment by loloof64** [comment]
It may be because of the fact that, as I said you above, the plugin was not developed with the lastest architecture of React Native (Turbo Modules).
It's been a while since I've been working on this project, and I'm not yet planning to code this plugin in the new architecture, which will involve some hard work on my own.
My priority is not targeted in React Native as for now.

I've not tested the application recently (I still does not have react native and android sdk installed in my new computer)

Maybe I will upgrade it later.

**Comment by FirePlank** [comment]
Does Turbo Modules offer multithreading? The .js files i saw were only a couple of lines defining the sendCommand, MainLoop and shutdown functions, the rest is the bridge and stockfish and the 2 .java files. Isn't the js the only files needed to be changed. If you are unable to continue maintaining this project, would you be able to help me look in the right direction to get this working. Be it using React Native Threads or converting the package to Turbo Modules.

**Comment by loloof64** [comment]
First, I'm apologizing, because TurboModules is still experimental : https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules

I'm going to install React-Native and test my example project on my device. Maybe I'll have to update the code accordingly, but keeping the old plugin architecture (not under TurboModule).

**Comment by loloof64** [comment]
Also, I forgot to say that this plugin is not intended for expo version, but for react-native cli.

**Comment by FirePlank** [comment]
Hi, great to hear you are going to check this out, I truly appreciate it! I am using expo but I have detached to bare workflow which should make it work identically to react-native so that should not be the problem, any react-native plugin will work on expo bare.

Thank you for taking your time to check this out.

**Comment by FirePlank** [comment]
Hi! Just following up on our last week's discussion. Have you made any breakthroughs in our predicament? Also, did you know that today is exactly the 1 year anniversary since you last made a commit on this repository!

**Comment by loloof64** [comment]
Hi, sorry. I had trouble upgrading the plugin.

So I'm resetting the project with a new version of **react-native-builder-bob** and then I'll set all required elements of the old project back.

**Comment by loloof64** [comment]
It's done 😃 
I've updated the plugin : you can run example and have a look at its code.

I've successfully ran it on a Phone with Android 5.0 and the latest react-native version.

I've also updated to the latest stable stockfish NNUE file.

Please, let me know if it works on your side.
(Please also note that you still won't be able to make hot reload.)

**Comment by loloof64** [comment]
Oups ! I've forgot to update the NPM package.

**Comment by loloof64** [comment]
Done now ! There is a version 0.3.0 in the NPM registry 😃 
Please, let me know if it works on your side. ❓

**Comment by FirePlank** [comment]
Hi! Thanks for taking your time to work on this. I installed your updated package and ran the same code as before but I still get the issue of the app freezing and not being interactive in any way until the search is finished. was this something you were meant to fix in this build or was it something else? How would I achieve a similar kind of analysis mode where the evaluation is displayed along side the board where you can make moves similar to https://lichess.org/analysis

**Comment by loloof64** [comment]
Have you tried to run the example first ? Does it run well on your emulator/device ?

**Comment by loloof64** [comment]
Closed as I did not get an answer since 5 months ago.

**Comment by Asad520** [comment]
@loloof64 Can you guide or explain what could be causing the issue with the hot reload? My app has this thing where it reloads the app using the [expo-updates](https://docs.expo.dev/versions/latest/sdk/updates/#updatesreloadasync). After the reload the engine stops responding.
I think if the hot reload is fixed, it'll also fix my issue. I've tried debugging the hot reload problem but could not find any good direction and have spent much time already. Any help would be really appreciated

**Comment by loloof64** [comment]
Hi ! I don't maitain this repository any more, but I've started some days ago a new one : [React Native Stockfish](https://github.com/loloof64/ReactNativeStockfish), with the new TurboModules architecture and Stockfish 15 as for now.

The example application runs fine on Android, but I've still got to fix some issues for IOS.

**Comment by FirePlank** [comment]
Is it finally async?

**Comment by loloof64** [comment]
I don't have tested the new version in a real project yet (just in the example in the subdirectory). But reading from the output and the errors is implemented to be async : you just pass callbacks in order to process them, and in the native side there are some coroutines in Android implementation, and Threads in IOS version.

Anyway, nothing prevents you from creating a new test project and try it (I did not try to send a new request to the engine while another one was pending, but according to me, it should work).

Last but not least, you must ensure that you shut down stockfish before processing an hot-reload

1. this will stop the main loop
2. this will also unregister the reading outputs/errors callbacks

Please, let me know if it worked for you.

**Comment by Asad520** [comment]
@loloof64, I appreciate your quick response. I tried using memory buffers, and with the help of GPT, it worked perfectly on both Android and iOS.
Thanks!

**Comment by loloof64** [comment]
Glad to know it works with your adjustments. Though I'm surprised to know you had to use memory buffer : was it only for IOS or also for Android ?

Also, as stated [here](https://github.com/loloof64/React-Native-Stockfish-Android/issues/2#issuecomment-2563573463), I'm working on a new version of this plugin :

1. I'm converting it to stockfish 17
2. It works fine on Android, but I've still some works to do to make it work for IOS
3. It uses the new React-Native architecture, gaining in performances

I'll put a note here when it's ready.

**Comment by Asad520** [comment]
I'm using Pikafish for a Xiangqi app. Pikafish uses Stockfish under the hood with some additional rules for Xiangqi. 
Yes, I used memory buffers for both Android & iOS. Used them to redirect the input and output stream buffers by inheriting the std::streambuf. 

`class CustomInputBuffer : public std::streambuf`
`class CustomOutputBuffer : public std::streambuf`

I've also used thread-safe queue with mutex. I can share the code with gists if it can help you building the new package.

**Comment by loloof64** [comment]
Thank you 😃 

Indeed, the streams handling is a hard part. Maybe I could get inspired by your solution if mine is not good in the new plugin.
As for now I just use a kind of fake cin and cout, got inspired by a package for flutter.

Also, I'm still trying to make it work fine on IOS, but I think I'm on the good path.
The thing is that I need to download NNUE files and somewhat place them into the source path of the plugin during the compilation of the target project.

So not as simple as it may seem.

I'll puts note here if I manage to do so.

**Comment by Asad520** [comment]
Happy to help.
Here are the gists:
- [PikafishEngine.mm](https://gist.github.com/Asad520/8dcfa3d42bd991ac3b4e99f9a8186983) for iOS
- [Piakfish.cpp](https://gist.github.com/Asad520/d024d491b46d1a80764376e42ac14268) JNI for Android
- [PikafishEngine.java](https://gist.github.com/Asad520/32c02bc24ccb6120468fec7124c1b0fc) for Android

For nnue support on iOS, I've added the .nnue file to the Resources directory by drag and drop in XCode and used the native method to get its path. Then set that path using sendCommand to the engine.

```
RCT_EXPORT_METHOD(getNNUEPath:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject) {
    NSString* path = [[NSBundle mainBundle] pathForResource:@"pikafish" ofType:@"nnue"];
    if (path) {
        resolve(path);
    } else {
        reject(@"file_not_found", @"NNUE file not found", nil);
    }
}
```

For nnue support on Android, I've made it a part of `android/app/src/main/assets/pikafish.nnue`. But the engine cannot access the assets directory (or I could not do so). So, I copy it to the app's files directory after installation. This method returns the path if the file already exists. Copies from assets and then returns the path otherwise. Then used the path to set in sendCommand to engine.

```
@ReactMethod
    public void getNNUEPath(Promise promise) {
        try {
            String fileName = "pikafish.nnue";
            Context context = getReactApplicationContext();
            File file = new File(context.getFilesDir(), fileName);

            // If the file doesn't exist, copy it from assets
            if (!file.exists()) {
                AssetManager assetManager = context.getAssets();
                try (InputStream inputStream = assetManager.open(fileName);
                      FileOutputStream outputStream = new FileOutputStream(file)) {

                    byte[] buffer = new byte[1024];
                    int length;
                    while ((length = inputStream.read(buffer)) > 0) {
                        outputStream.write(buffer, 0, length);
                    }
                }
            }

            // Return the file's absolute path
            promise.resolve(file.getAbsolutePath());
        } catch (IOException e) {
            promise.reject("file_error", "Error accessing NNUE file", e);
        }
      }
```

Let me know if you wanna know anything else

**Comment by loloof64** [comment]
Thank you very much.

I may also be able to download the nnue files automatically from the Pods installation step. Still trying to fix some little issue.
If I manage, it will be available in [the new version](https://github.com/loloof64/ReactNativeStockfish).
